# Generated by Django 6.0.4 on 2026-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="charged_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
