# Generated by Django 6.0.4 on 2026-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translater", "0002_video_charged_seconds_video_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="is_charge_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
