# Generated by Django 6.0.4 on 2026-05-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_pendingregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
    ]
