# Generated by Django 6.0.4 on 2026-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_google_auth",
            field=models.BooleanField(default=False),
        ),
    ]
