# Generated by Django 6.0.4 on 2026-05-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_google_auth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="credits",
            new_name="avalible_seconds",
        ),
    ]
