# Generated by Django 6.0.4 on 2026-05-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_credits_user_avalible_seconds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avalible_seconds",
            new_name="available_seconds",
        ),
    ]
