# Generated by Django 6.0.4 on 2026-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_avalible_seconds_user_available_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingregistration",
            name="legal_docs_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="offer_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="privacy_policy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="registration_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="legal_docs_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="offer_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
